SignalViewer:
    VerticalCursorColor: g
    CursorsShowValue: yes
    LinkedVerticalCursorColor: violet
    CursorHoverColor: tomato
Fconf:
    name: np.linalg.norm
    args: []
    kwargs:
        axis: 0
        ord: 2
